region: ap-northeast-1
cluster: '{{ must_env "AWS_ACCOUNT_ID" }}-{{ must_env "ENV" }}-admin-frontend'
service: '{{ must_env "AWS_ACCOUNT_ID" }}-{{ must_env "ENV" }}-admin-frontend'
task_definition: ecs-task-def.json
timeout: "10m0s"
