spring:
  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: true
      file: compose.yml
      lifecycle-management: start-and-stop

logging:
  level:
    com.mametosho: DEBUG
    org.mybatis: DEBUG
