name: Deploy SchemaSpy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/db/schema.sql
      - .github/workflows/github-pages.yml
  workflow_dispatch:

  pull_request:
    branches: [main]
    paths:
      - .github/workflows/github-pages.yml

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  scemaspy-build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import schema
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/infrastructure/db:/sql \
            mysql:8.0 \
            mysql --default-character-set=utf8 \
            -h127.0.0.1 -P3306 -uroot -proot app -e "source /sql/schema.sql"

      - name: Run SchemaSpy
        run: |
          mkdir -p schemaspy-output
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/schemaspy-output:/output \
            schemaspy/schemaspy:latest \
            -t mysql \
            -host 127.0.0.1 \
            -port 3306 \
            -db app \
            -u root \
            -p root

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: schemaspy output
          path: ./schemaspy-output

  deploy:
    needs: [scemaspy-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Schemaspy output
        uses: actions/download-artifact@v3
        with:
          name: schemaspy output
          path: ./output/schemaspy

      - name: Upload page artifact 
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
